### ISSUE TITLE
Q4 2020 roadmap

### ISSUE THREAD

**Issue by profilemyprofile** [profilemyprofile/router#1]
**Фичи:**
- [x] ~~Навигация~~
- [x] ~~Управление навигацией системными кнопками назад / вперёд~~
- [x] ~~Параметры текущей записи в навигации~~
- [x] ~~Обработка ссылок вида vk.com/app000#panel=info~~
- [ ] iOS Swipeback
- [x] ~~Управление модальными окнами~~
- [ ] Управление попаутами
- [x] ~~Управление снэкбарами~~
- [ ] Фантомные записи
- [x] ~~Передача состояния в ``useStructure`` (даёт возможность сделать начальную структуру фантомной)~~
- [ ] Обертки над хуками в виде компонентов

**Баги:**
- [x] ~~Первый рендер приложения происходит два раза~~
- [ ] Ломается навигация при быстром переходе на другое состояние
- [ ] Неправильное поведение ``useLocation`` при первом рендере

**Документация:**
- [ ] Описание пакета
- [ ] Установка
- [ ] Быстрый старт
- [ ] Структура приложения
- [ ] Управление навигацией
- [ ] Управление модальными окнами
- [ ] Управление снэкбарами
- [ ] Передача параметров панелям
- [ ] Работа с хэшем
